#!/bin/sh
# Based on https://github.com/diffplug/spotless/issues/178#issuecomment-351638034
# install by running `git config core.hooksPath utils/git-hooks` in your repo root

echo '[git hook] executing gradle spotlessApply before commit'

# stash any unstaged changes
git stash -q --keep-index

# run the spotlessApply with the gradle wrapper
./gradlew spotlessApply

# store the last exit code in a variable
RESULT=$?

# unstash the unstashed changes
git stash pop -q

# return the './gradlew spotlessApply' exit code
exit $RESULT
