plugins {
    id "com.gradleup.shadow" version "${shadow_version}"
}

repositories {
    maven { url 'https://maven.neoforged.net/releases'}
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    neoForge {
        convertAccessWideners(tasks.named("shadowJar", Jar), "wynntils.accessWidener")
    }
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common
    // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
    shadowCommon
    implementation.extendsFrom shadowImplementation
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

dependencies {
    neoForge "net.neoforged:neoforge:${neoforge_version}"
    runtimeOnly "me.djtheredstoner:DevAuth-neoforge:${devauth_version}"

    common(project(path: ":common")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionNeoForge")) { transitive false }

    // Hades Protocol
    if (file("${rootDir}/../Hades/build/libs/HadesProtocol-${hades_version}.jar").exists()) {
        shadowImplementation(files("${rootDir}/../Hades/build/libs/HadesProtocol-${hades_version}.jar"))
    } else {
        shadowImplementation("com.github.wynntils:hades:v${hades_version}") { transitive false }
    }
    include(forgeRuntimeLibrary("com.github.wynntils:antiope:v${antiope_version}"))

    implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixinextras_version}"))
    implementation(include("io.github.llamalad7:mixinextras-neoforge:${mixinextras_version}"))
}

processResources {
    var replaceProperties = [
            mod_version                : rootProject.version,
            minecraft_version          : neoforge_minecraft_version_range,
            neoforge_version_range     : neoforge_version_range,
            loader_version_range       : neoforge_loader_version_range,
            mod_id                     : mod_id
    ]
    inputs.properties replaceProperties

    filesMatching([
            'META-INF/neoforge.mods.toml',
            'pack.mcmeta'
    ]) {
        expand replaceProperties
    }
}

shadow {
    addShadowVariantIntoJavaComponent = false
}

jar {
    archiveClassifier = "raw"
}

shadowJar {
    exclude "fabric.mod.json"
    dependsOn(jar)
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))

    configurations = [
            project.configurations.shadowCommon,
            project.configurations.shadowImplementation
    ]

    archiveClassifier = "neoforge+MC-${minecraft_version}"
    from rootProject.file("LICENSE.md")
}

sourcesJar {
    afterEvaluate {
        def depSources = project(":common").sourcesJar
        dependsOn depSources
        from(depSources.archiveFile.map { zipTree(it) }) {
            exclude "wynntils.accessWidener"
        }
    }
    archiveClassifier = "neoforge+MC-${minecraft_version}-sources"
}
