name: Publish Alpha Release

on:
  push:
    branches:
      - alpha

jobs:
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.changelog.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}
      clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
      changelog: ${{ steps.changelog.outputs.changelog }}
      release_id: ${{ steps.release.outputs.id }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PRIVATE_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm install conventional-changelog-conventionalcommits

      - name: Set up version.json
        run: echo "{"version":$(git describe --tags --abbrev=0)}" > version.json

      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5.2.1
        with:
          github-token: ${{ secrets.PRIVATE_TOKEN }}
          git-user-name: 'WynntilsBot'
          git-user-email: 'admin@wynntils.com'
          pre-commit: ./.github/.pre-commit.js
          config-file-path: ./.github/.config.js
          version-file: ./version.json
          skip-version-file: true
          skip-git-pull: true
          pre-release: true
          pre-release-identifier: alpha
          release-count: 5

      - name: Create release
        if: ${{ steps.changelog.outputs.skipped != 'true' }}
        id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: true
          prerelease: true

      - name: Upload version information
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build.gradle
          overwrite: true

  build:
    name: Build
    needs: [ changelog ] # Build needs the new version number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Gradle data
        uses: actions/cache@v4
        with:
          path: .gradle
          key: ${{ runner.os }}-gradle--${{ hashFiles('**/settings.gradle', '**/gradle.properties') }}

      - uses: actions/download-artifact@v4 # Download version information from changelog
        with:
          name: build

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: buildDependents -x spotlessCheck -x test

      - name: Upload files to release
        uses: softprops/action-gh-release@v2
        if: ${{ needs.changelog.outputs.skipped != 'true' }}
        with:
          tag_name: ${{ needs.changelog.outputs.tag }}
          draft: true
          prerelease: true
          files: |
            **/build/libs/*-fabric+MC-*.jar
            **/build/libs/*-forge+MC-*.jar

  release-gh:
    name: Release Github
    if: ${{ needs.changelog.outputs.skipped != 'true' }}
    runs-on: ubuntu-latest
    needs: [ build, changelog ]
    steps:
      - name: Publish Release
        uses: eregon/publish-release@v1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.changelog.outputs.release_id }}
